import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ImagesPane from "../components/ImagesPane";
import Details from "../components/Details";
import Header from "../components/Header";

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Host Lequie Artstic</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <Header />
            <div className={styles.box}>
               <div style={{ flex: 0.4 }}>
                  <ImagesPane />
               </div>
               <div style={{ flex: 0.6 }}>
                  <Details />
               </div>
            </div>
         </main>
      </div>
   );
}
